/*
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Internal SDK compatibility constants used by APR AIO/equeue code.
 */

#pragma once

#include <_kernel.h>
#include <kernel.h>

#ifndef SCE_KERNEL_EV_ADD
  #define SCE_KERNEL_EV_ADD 0x0001
#endif
#ifndef SCE_KERNEL_EV_DELETE
  #define SCE_KERNEL_EV_DELETE 0x0002
#endif
#ifndef SCE_KERNEL_EV_ENABLE
  #define SCE_KERNEL_EV_ENABLE 0x0004
#endif
#ifndef SCE_KERNEL_EV_DISABLE
  #define SCE_KERNEL_EV_DISABLE 0x0008
#endif
#ifndef SCE_KERNEL_EV_ONESHOT
  #define SCE_KERNEL_EV_ONESHOT 0x0010
#endif
#ifndef SCE_KERNEL_EV_CLEAR
  #define SCE_KERNEL_EV_CLEAR 0x0020
#endif
#ifndef SCE_KERNEL_EV_DISPATCH
  #define SCE_KERNEL_EV_DISPATCH 0x0080
#endif
#ifndef SCE_KERNEL_EVFILT_AMPR_SYSTEM
  #define SCE_KERNEL_EVFILT_AMPR_SYSTEM SCE_KERNEL_EVFILT_AMPR
#endif
#ifndef SCE_KERNEL_AIO_PRIORITY_LOW
  #define SCE_KERNEL_AIO_PRIORITY_LOW 1
#endif
#ifndef SCE_KERNEL_AIO_PRIORITY_MID
  #define SCE_KERNEL_AIO_PRIORITY_MID 2
#endif
#ifndef SCE_KERNEL_AIO_PRIORITY_HIGH
  #define SCE_KERNEL_AIO_PRIORITY_HIGH 3
#endif
#ifndef SCE_KERNEL_AIO_REQUEST_NUM_MAX
  #define SCE_KERNEL_AIO_REQUEST_NUM_MAX 128
#endif
#ifndef SCE_KERNEL_AIO_ENABLE_SPLIT
  #define SCE_KERNEL_AIO_ENABLE_SPLIT 1
#endif
#ifndef SCE_KERNEL_AIO_DISABLE_SPLIT
  #define SCE_KERNEL_AIO_DISABLE_SPLIT 0
#endif
#ifndef SCE_KERNEL_AIO_SPLIT_SIZE_MAX
  #define SCE_KERNEL_AIO_SPLIT_SIZE_MAX 0x1000000
#endif
#ifndef SCE_KERNEL_AIO_SPLIT_CHUNK_SIZE_MAX
  #define SCE_KERNEL_AIO_SPLIT_CHUNK_SIZE_MAX 0x1000000
#endif
#ifndef SCE_KERNEL_AIO_SCHED_WINDOW_DEFAULT
  #define SCE_KERNEL_AIO_SCHED_WINDOW_DEFAULT 32
#endif
#ifndef SCE_KERNEL_AIO_DELAYED_COUNT_DEFAULT
  #define SCE_KERNEL_AIO_DELAYED_COUNT_DEFAULT 32
#endif
#ifndef SCE_KERNEL_AIO_STATE_COMPLETED
  #define SCE_KERNEL_AIO_STATE_COMPLETED 3
#endif
#ifndef SCE_KERNEL_AIO_STATE_ABORTED
  #define SCE_KERNEL_AIO_STATE_ABORTED 4
#endif
#ifndef SCE_KERNEL_AIO_STATE_NOTIFIED
  #define SCE_KERNEL_AIO_STATE_NOTIFIED 0x10000
#endif
